# TODO (if using conda) - complete with environment name and dependencies
# Refer to the course and follow the best practices for creating a conda environment
name: xhec-mlops-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.2.1
  - pip-tools=7.3.0
  - pip:
      - -r requirements.txt
      - -r requirements-dev.txt
